[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Headers for proper MIME types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Favicon and icon headers
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/favicon.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/apple-touch-icon.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/icon-192.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Remove build processing to avoid conflicts
# [build.processing]
#   skip_processing = false

# [build.processing.css]
#   bundle = true
#   minify = true

# [build.processing.js]
#   bundle = true
#   minify = true

# [build.processing.html]
#   pretty_urls = true
